USE sakila;

# List the number of films per category.
SELECT 
    category.name AS category,
    COUNT(film.film_id) AS number_of_films
FROM film
INNER JOIN film_category ON film.film_id = film_category.film_id
INNER JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name
ORDER BY number_of_films DESC;

# Retrieve the store ID, city, and country for each store.
SELECT 
	store.store_id AS store,
    city.city AS city,
    country.country AS country
FROM store
INNER JOIN address ON store.address_id = address.address_id
INNER JOIN city ON  address.address_id = city.city_id
INNER JOIN country ON city.country_id = country.country_id;

# Calculate the total revenue generated by each store in dollars.
SELECT
	store.store_id AS store,
	SUM(payment.amount) AS total_revenue
FROM store
INNER JOIN customer ON store.store_id = customer.store_id
INNER JOIN payment ON customer.customer_id = payment.customer_id
GROUP BY store;

# Determine the average running time of films for each category.
SELECT
    category.name AS category,
    ROUND(AVG(film.length), 0) AS average_length
FROM film
INNER JOIN film_category ON film.film_id = film_category.film_id
INNER JOIN category ON film_category.category_id = category.category_id
GROUP BY category.name
ORDER BY average_length DESC;

# Bonus:
# Identify the film categories with the longest average running time.
# Display the top 10 most frequently rented movies in descending order.
# Determine if "Academy Dinosaur" can be rented from Store 1.
# Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."



# Decide which table you want to use as the left table (immediately after FROM) and which will be the right table (immediately after JOIN).
# If you want all records from the first table, use a LEFT JOIN. If you want all records from the second table, use a RIGHT JOIN. If you want records from both tables only where there is a match, use an INNER JOIN.